### ISSUE TITLE
Wireguard routing table entries weird?

### ISSUE THREAD

**Issue by graza** [chewitt/connman#1]
https://github.com/chewitt/connman/blob/7be4fae63b01c44479367bd47bd655f104425db8/doc/vpn-config-format.txt#L344

I've been using Wireguard since late 2018 to access my home network.  I was recently trying to use the connman configuration but I don't understand how to get the routing table entries I want.  I only want to route specific subnets to my Wireguard server but connman seems to always make the VPN the default.

Oh, and it doesn't work.  I can't ping the peer, even though it seems to have been connected OK.

```
# wg show
wg show
interface: wg0
  public key: keyhidden
  private key: (hidden)
  listening port: 49423

peer: keyhidden
  endpoint: redacted
  allowed ips: 192.168.5.0/24
  latest handshake: 41 seconds ago
  transfer: 92 B received, 212 B sent
  persistent keepalive: every 25 seconds

# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         0.0.0.0         0.0.0.0         U     0      0        0 wg0
192.168.2.0     0.0.0.0         255.255.255.0   U     0      0        0 eth0
192.168.2.1     0.0.0.0         255.255.255.255 UH    0      0        0 eth0
192.168.5.0     0.0.0.0         255.255.255.0   U     0      0        0 wg0
255.255.255.255 192.168.2.1     255.255.255.255 UGH   0      0        0 eth0

```

I've tried using the Networks option but it doesn't seem to do anything with Wireguard.  This is on LibreELEC v9.2.6.

Any ideas?

**Comment by chewitt** [comment]
https://forum.libreelec.tv
